In [1]:
import pandas as pd
nba = pd.read_csv("C:\\Users\\ASUS\\Desktop\\NBA\\data\\nba_data.csv")
nba.describe()

,Rk,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
count,595.000000,595.000000,595.000000,595.000000,595.000000,595.000000,595.000000,593.000000,595.000000,595.000000,...,571.000000,595.000000,595.000000,595.000000,595.000000,595.000000,595.000000,595.000000,595.000000,595.000000
mean,244.114286,26.411765,48.431933,22.136134,19.536471,3.034622,6.733445,0.441282,0.762857,2.169244,...,0.737637,0.825378,2.668067,3.490756,1.753950,0.608403,0.390924,1.080504,1.674286,8.186387
std,140.605917,4.261273,26.306597,27.427160,8.841753,2.080916,4.373783,0.102820,0.740244,1.892715,...,0.150574,0.761452,1.796496,2.425385,1.696807,0.409397,0.476857,0.768437,0.756984,5.842241
min,1.000000,19.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,124.500000,23.000000,24.000000,0.000000,12.700000,1.500000,3.600000,0.400000,0.200000,0.600000,...,0.667000,0.300000,1.400000,1.800000,0.600000,0.300000,0.100000,0.500000,1.150000,4.200000
50%,244.000000,26.000000,55.000000,8.000000,18.800000,2.500000,5.600000,0.442000,0.600000,1.800000,...,0.765000,0.600000,2.300000,2.900000,1.200000,0.500000,0.300000,0.900000,1.600000,6.600000
75%,364.500000,29.000000,73.000000,39.000000,26.300000,4.100000,8.900000,0.485000,1.200000,3.400000,...,0.833000,1.100000,3.400000,4.600000,2.300000,0.800000,0.500000,1.450000,2.200000,10.700000
max,486.000000,40.000000,82.000000,82.000000,37.800000,10.300000,24.000000,1.000000,4.100000,10.000000,...,1.000000,4.300000,10.300000,14.100000,11.200000,2.000000,6.000000,5.700000,4.400000,31.600000